name: Send bug to Discord

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"New Bug: ${{ github.event.issue.title }}\n${{ github.event.issue.body }}\"}" \
          YOUR_WEBHOOK_URL
